### ISSUE TITLE
Serve API for events

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#16]
We have new Index on ElasticSearch for monitoring event. We need to serve API to be able to query

## Acceptance criteria

* [ ] Able to request `metastore/search/events` and get events

## Tasks

* [x] Decide on endpoint
  * metastore/search/events
* [x] handle "kind" events
* [x] handle quring new index
* [x] handle sorting by timestamp
* [x] test

**Comment by zelima** [comment]
FIXED
