### ISSUE TITLE
Old dataset that never successfully "built" appear in search

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#21]
@zelima commented on [Mon Dec 18 2017](https://github.com/datahq/pm/issues/81)

If you visit search page and click on around first 10 packages all of them will result in 404. Those are older packages that do not have any successful revisions. 

## Acceptance Criteria 

* [ ] no metadata exists in search DB if dataset failed to build
* [ ] If dataset is in search clicking it should result with nice showcase page

## Tasks 

* [ ] Identify brocken datasets (make list) - @Mikanebu 
* [ ] delete from ElastiSearch manually (???)

**Comment by rufuspollock** [comment]
@zelima could you explain why we end up with metadata in the metastore - if there is a good reason we may want to keep this but just ensure they don't show up in search ...

**Comment by zelima** [comment]
@rufuspollock I'm not sure I know the exact reason, but I guess at the beginning, even before going alfa, we cleared out some unnecessary data from database for some reasons, but forgot about elasticsearch.

**Comment by zelima** [comment]
@Mikanebu think we deleted these datasets right? can you double check?

**Comment by Mikanebu** [comment]
@zelima yes, it is FIXED is this issue https://github.com/datahq/pm/issues/92
