### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by svetozarstojkovic** [datahq/metastore#23]
As a Consumer looking for data I want to get a dataset on topic X so that I can use it for my work

As a Consumer looking for data I want to be able to search with relevant terms and see if there are datasets available that are related

* I want best matches in terms of topic
* I prefer better quality data (e.g. core datasets) to less good (or less reputable people)

What's the situation now:

* Have search page
* But just searching dataset titles - and should search README too (but higher weighting for title)
  * keywords??
* core datasets come last after alternatives ...

## Acceptance Criteria

* [ ] Search for finance brings up vix? Search for climate brings up co2-ppm
  * [ ] Searching for terms in the README works
* [ ] Search for a username should bring up their datasets (?:)
* [ ] core datasets get preference ... (so top of the list by default e.g. with empty query)

## Tasks

* [x] Do elasticsearch analysis [2.5h]
  * [x] Take a look at existing code and understand how it works [1h]
  * [x] Install run Elastic search [0.5h]
  * [x] Play around with elastic search and put there stuff (Taken from metastore API) [1h]
* [ ] Do techincal analysis [1.5h]
  * [ ] How does keywords work with elasticsearch [0.5h]
  * [ ] Find out how may core datasets get preference[1h]
* [ ] Propose solution in the analysis solution 
* [x] Write failing tests [1h]
* [x] make changes and pass the failing test [4h]

## Analysis

Repos to work with:
* Search logic:  https://github.com/datahq/metastore/blob/master/metastore/models.py
* Indexing the ElasticSearch: https://github.com/datahq/assembler/blob/master/datapackage_pipelines_assembler/processors/dump_to_s3.py

**Comment by zelima** [comment]
@svetozarstojkovic please assign to yourself, estimate an add to the Jan1st milestone

**Comment by svetozarstojkovic** [comment]
* Python tests for readme search are passing

## Acceptance Criteria

* [ ] Search for finance brings up vix? Search for climate brings up co2-ppm
  * [ ] Searching for terms in the README works
* [ ] Search for a username should bring up their datasets (?:)
* [ ] core datasets get preference ... (so top of the list by default e.g. with empty query)

## Tasks
* [ ] Run elasticsearch on local server [0.5d]
* [ ] Check frontend for errors in search [2d]
    * [ ] Frontend analysis [0.5d]
    * [ ] Deploy frontend on localhost [1d]
    * [ ] Make search hit local elasticsearch [0.5d]
* [ ] Title carries more weight when searching [1d]
* [ ] Core datasets have bigger score [2d]
    * [ ] ES analyze how some field having specific value gain higher score  [1d]
    * [ ] make changes to code [1d]
    
# Analysis

metastore: https://github.com/datahq/metastore
frontend: https://github.com/datahq/frontend

For searching in python exact instance of random dataset is used and readme search works.

Next thing to test is frontend, and follow whole path between frontend input field to elasticsearch service, to find exactly what is not working.

**Comment by zelima** [comment]
Issue moved to [datahq/pm #89](https://github.com/datahq/pm/issues/89) via [**ZenHub**](https://www.zenhub.com/)
