### ISSUE TITLE
In some cases core datasets are not getting boosted 

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#27]
Originally comming from here https://github.com/datahq/datahub-qa/issues/70 Sometimes core dataset do not appear on the top. 

## Acceptance Criteria

* [x] Core is always prefered 

## Tasks 

* [x] add the failing test
* [x] find the bug

**Comment by zelima** [comment]
FIXED

**Comment by AcckiyGerman** [comment]
If I search for Mauna Loa, the core dataset is not on the top :cry:

**Comment by zelima** [comment]
@AcckiyGerman that is expected - Mauna Loa, does not appear in Title for core, while for others it does. If phrase appears in title - it's the best match
