### ISSUE TITLE
Search phrases instead of single words

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#28]
As a user, I want to get matches for an exact Phrases and not for all words in phraze, so that I that I have only high quality serch result. 

## Acceptance Criteria

* [x] searching "United Nations" should not bring "Unitet states"
* [x] "the Mauna Loa" does not bring everything that includes "the"

## Tasks

* [x] failing test
* [x] fix the bug

**Comment by zelima** [comment]
FIXED
