### ISSUE TITLE
Disable phrase search

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#29]
Originally coming from here https://github.com/datahq/datahub-qa/issues/170#issuecomment-376768055

We need to search words instead of phrases to get better matches as users might include various stopwords while they search like and, or, no etc...

## Acceptance Criteria

* [x] results with examples dataset on top http://datahub.io/search?q=Aggregation+into+UK+Gross+Domestic+
* [x] results with examples dataset on top - http://datahub.io/search?q=Aggregation+UK+Gross+Domestic+
* [ ] results with core dataset on top http://datahub.io/search?q=the+UK+Gross+Domestic+
* [ ] results with core dataset on top http://datahub.io/search?q=UK+Gross+in+Domestic
* [ ] results with 3 datasets http://datahub.io/search?q=Mauna+Loa
* [ ] results with 3 datasets http://datahub.io/search?q=the+Mauna+Loa

## Tasks 

* [ ] remove phrase search

**Comment by zelima** [comment]
FIXED
