### ISSUE TITLE
searching "country list" results with unexpected result

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#30]
Originally coming from https://github.com/datahq/datahub-qa/issues/189

Search acts weirdly if you try and search "country list". It results with pharmaceutical drugs dataset with a better score.

## Acceptance Criteria

* [ ] country list results in the "country list" dataset

## Tasks

* [ ] failing tests
* [ ] find the bug and do analysis 
* [ ] come up with solution

## Analysis

Going deep to elastic search scoring system I've got the following: 

* Elasticsearch is choosing a result from the shard with the best score. 

That can be fixed by defining  `'search_type'` to be equal to `'dfs_query_then_fetch'` instead of the default `query_then_fetch`. While this seems the solution and we are getting better results (not yet best) it leads to 2 problems.

* performance issue, as the number of documents increase search speed will decrease significantly 
* We are still not getting the best match: instead of `Pharmaceutical Drug Spending by countries` now we are getting `nasdaq-listings` datasets with the highest score and `country-list` dataset on second place. 

Investigating and analysing this further I discovered that the scores (that results the difference) ar calculate in the following way:

```
score = (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength))
```

Where all the variables are identical instead of `fieldLength`: 

* In case of `nastdaq-listing` it's 2 (two words in the title `Nasdaq Listings`)
* In case of `country-list` it's 10 (10 words in title `List of all countries with their 2 digit codes (ISO 3166-1)`)

The difference given by these numbers is so big that even considering the fact that `country-list` contains another match "country" the sum is still less then score of single "list" appeared in `nasdaq-listing`

**Possible solutions**

* give a short title to the country list dataset and provide a nice description.
* Introduce keywords - another property in `datapackage.json` and boost it more than everything else. Core curators will have to work on keywords a bit and push the dataset to get better search results
* ??? switch to BM25 ranking mechanism (E.S 6.X) that calculates scores in the better ways then Lucene 6 as recommended by many articles. (Not sure it will help to solve this issue https://github.com/elastic/elasticsearch/issues/25916)

To visualize here is the `tfNorm`  - one of the multipliers to get the score for both of them - country list and nasdaq list (others multipliers are exactly equall) :

Explain for `country-lists`
```
{
  "value" : 0.6069876,
  "description" : "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
  "details" : [
    {
      "value" : 1.0,
      "description" : "termFreq=1.0",
      "details" : [ ]
    },
    {
      "value" : 1.2,
      "description" : "parameter k1",
      "details" : [ ]
    },
    {
      "value" : 0.75,
      "description" : "parameter b",
      "details" : [ ]
    },
    {
      "value" : 3.964798,
      "description" : "avgFieldLength",
      "details" : [ ]
    },
    {
      "value" : 10.24,
      "description" : "fieldLength",
      "details" : [ ]
    }
  ]
}
```

Explain for `nasdaq-listing`
```
{
  "value" : 1.1695197,
  "description" : "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
  "details" : [
    {
      "value" : 1.0,
      "description" : "termFreq=1.0",
      "details" : [ ]
    },
    {
      "value" : 1.2,
      "description" : "parameter k1",
      "details" : [ ]
    },
    {
      "value" : 0.75,
      "description" : "parameter b",
      "details" : [ ]
    },
    {
      "value" : 3.964798,
      "description" : "avgFieldLength",
      "details" : [ ]
    },
    {
      "value" : 2.56,
      "description" : "fieldLength",
      "details" : [ ]
    }
  ]
}
```

As a result to get the final score, multiplying one by `1.16...` and other by `0.6...`  results in big difference.

**Comment by akariv** [comment]
@zelima -
1. When searching for "list of countries", which comes first?
2.

**Comment by zelima** [comment]
@akariv 

1. getting the same result
2. we are already using multi-fields
3. we've just moved back to match any result instead of all `phrase search ==> word search` see discussion here https://github.com/datahq/datahub-qa/issues/170#issuecomment-376768055
4. So I guess this remains the only option 

Also, what do you think about DFS Query Then Fetch VS Query Then Fetch: https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch

**Comment by akariv** [comment]
If we're using multi fields, we could boost the exact matches over the inexact ones, no?
So that `list of countries`, which exact-matches `List of all countries with their 2 digit codes (ISO 3166-1))`, will get a better score than `Nasdaq Listings` which doesn't have exact matches.

**Comment by zelima** [comment]
FIXED
* moved `search_type`  to be `dfs_query_then_fetch` from default `query_then_fetch` (score is calculate accross the shards)
* bumped core boost by 0.5 
* Moved to `'type': 'most_fields'` from defaul `'type': 'all_fields'`
