### ISSUE TITLE
Do analysis for how data is appearing when no argument is passed in the search page

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#32]
As a product manager I want to show top datasets by default, Eg right now 'population growth' is the first result, however, we want to show 'finance-vix' or others that are updated regularly and have graphs, so that users have feeling that there are more high-quality data on datahub

## Acceptance Criteria

* [ ] We know exactly why this or that dataset appears.
* [ ] Change behaviour as desired if possible

## Tasks

* [ ] do the analysis 

## Analysis

So few things we can do here:

1. sort results by `modified` date. This will result in the latest data to appear first instead of "core". So not quite an option 
2. Sort by dataset name/title. But again not quite what we want + this can use significant memory
3. introduce "datahub.popualrity" or similar property in dp.json and count views, somehow update/save dataset metadata with that info and sort by counts. --> quite big item and think really hard to implement.
4. Choose 10 most popular datasets and boos their titles by directly hard coding in metastore codebase. --> Not clean, may affect other search results
5. Leave metastore as is and re-sort in frontend. But again not clean

Ideally, probably we need N3, but think that's a really big Item, cause few questions come up right away:
* How are we going to export data in ES, directly from frontend? 
* How will processors get those number on new revision (processors have no clue about the previous dp.json)

If we really want this, think the most optimal way is N4 or N5.

**Comment by zelima** [comment]
@anuveyatsu could you please take a look a the analysis and share what do you think? 

\cc @rufuspollock @akariv any better ideas maybe?

**Comment by anuveyatsu** [comment]
We're considering this issue because the Search page is one of our most visited pages and as it can be seen from the analytics, users are just exploring what we have on the Datahub (not looking for particular data). So that they usually just click on the first item in the list.

I think we **should not** display search results when there is no query and this would solve the issue. Since we're working on a redesign of the page, we can think of a new layout when a user arrives on the page and no query was typed yet. E.g., we can show the selected datasets (top 5-10) in the frontend without changes in the metastore.

@zelima

**Comment by zelima** [comment]
:+1:

**Comment by zelima** [comment]
Closing as FIXED
