### ISSUE TITLE
Reindex elasticsearch

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#34]
As a developer I want to have a simple code in gist to reindex elasticsearch, so that I don't have to search again and again in google how to. 

## Acceptance Criteria

* [x] Have simple code with instructions how to reindex on gist

## Tasks 

* [x] write the code
* [x] gist it https://gist.github.com/zelima/ea324891ee4692db940192ecb9c96820

**Comment by zelima** [comment]
FIXED
