### ISSUE TITLE
Refactor tests to not to use PackageRegistry

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#4]
Our current tests are depended on `PackageRegistry` from [os package registry](https://github.com/openspending/os-package-registry/blob/master/os_package_registry/package_registry.py#L8). We are not going to use it further so we don't need it.

Also we do not have conception of `models` for datahub (for what os_package_registry was mostly used (saving, creating, deleting models)).

## Acceptance criteria 

* [ ] no `os_package_registry` in deps

## Tasks 

* [ ] remove it from deps
* [ ] remove `models` form [ENABLED_SEARCHES](https://github.com/datahq/metastore/blob/master/metastore/models.py#L14)
  * [ ] even remove whole `_source`
* [ ] update tests

**Comment by zelima** [comment]
FIXED
