### ISSUE TITLE
API refactor 

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#5]
Currently, metastore API is not useful as it does not query against update schema (see #1). We need to refactor it to search datasets via datapackage.json

## acceptance criteria

* [x] able to search dataset on `/metasore/search?q=data`

## Tasks

* [x] refactor tests
* [x] refactor functions
  * [x] `build_dsl()` https://github.com/datahq/metastore/blob/master/metastore/models.py#L38
  * [x] `query()` https://github.com/datahq/metastore/blob/master/metastore/models.py#L91

## Analysis 

/metastore/search

Method: GET

HEADER:

Auth-Token: authentication token (received from /user/check)

Query Parameters:

q - match-all query string
size - number of results to return [max 50]
from - offset to start returning results from
all other parameters will be treated as filters for the query (requiring exact match of value)

Returns:

All packages that match the filter

### Some examples

`/metastore/search?q=finance&datahub.owner=core`
=>

Find all datasets that have owner username of core and where finance matches (readme or title or keywords with heavier weighting on title) and where findability is published.

```
Auth-Token: jwt for user core
/metastore/search?q=finance&datahub.owner=core
```
Same as above but show private and unlisted packages for core.

```
Auth-Token: jwt for user core
/metastore/search?q=finance
```
Find all datsets that match finance and show packages with findability published for others and for core that are private or unlisted.

**Comment by zelima** [comment]
FIXED in #6
