### ISSUE TITLE
Filter with findability

### ISSUE THREAD

**Issue by zelima** [datahq/metastore#7]
We want to filter results with `findability` so that we don't display private, or deleted packages - one of: 
* published
* unlisted
* private

## Acceptance criteria

* [ ] by default getting only published ones
* [ ] if token provided - getting private and unlisted ones for user with that token

## Tasks

* [ ] refactor logic for filtering https://github.com/datahq/metastore/blob/master/metastore/models.py#L43
* [ ] test it

**Comment by zelima** [comment]
FIXED. This was already done here https://github.com/datahq/metastore/blob/master/metastore/models.py#L51 and tested here https://github.com/datahq/metastore/blob/master/tests/test_controllers.py#L215 and here https://github.com/datahq/metastore/blob/master/tests/test_controllers.py#L226
